version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: chessdev
      POSTGRES_PASSWORD: chessdev123
      POSTGRES_DB: chessdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    ports:
      - "8090:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
