spring:
  application:
    name: auth-service
    security:
      jwt:
        secret: 7rIx2CnWZi9oO9Yqb/mk8NUX0mjFClQ3MHiOUzOTpV4=
        access-token-expiration: 900000 # 15 minutes
        refresh-token-expiration: 604800000 # 7 days

  
  datasource:
    url: jdbc:postgresql://localhost:5432/chessdb
    username: chessdev
    password: chessdev123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: 8081
  servlet:
    context-path: /api/auth



logging:
  level:
    com.chess.auth: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html