spring:
  application:
    name: game-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chessdb
    username: chessdev
    password: chessdev123
    driver-class-name: org.postgresql.Driver

  jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         format_sql: true
         order_updates: true
         order_inserts: true
     show-sql: true
  
server:
  port: 8082
  servlet:
    context-path: /api/game

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.chess.game.service: DEBUG
